package excepion_handling1;

public class arithmatic_
{

	public static void main(String[] args) 
	{
		try
		{
		int a=10,b=0,c;
		c=a/b;
		System.out.println(c);
		}
		catch(Exception e)
		{
			System.out.println("arithmatic exception");
		}
	}

}
